[package]
name = "wyw_wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
itertools = "0.13.0"
oxc = "0.30.5"
regex = "1.11.0"
wasm-bindgen = "0.2.95"
wyw_shaker = { path = "../wyw_shaker" }

console_error_panic_hook = { version = "0.1.7", optional = true }
cfg-if = "1.0.0"

[dev-dependencies]
wasm-bindgen-test = "0.3.35"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"