[package]
name = "wyw_traverse"
version = "0.1.0"

edition.workspace = true
rust-version.workspace = true

[dependencies]
oxc = { workspace = true }
oxc_semantic = { workspace = true }
wyw_macros = { workspace = true }
