[package]
name = "rust-shaker"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies]
serde = "1"
log = "0.4.21"
serde_json = "1.0.114"
oxc = "0.30.5"
oxc_codegen = "0.30.5"
oxc_traverse = "0.30.5"
oxc_semantic = "0.30.5"
glob = "0.3.1"
oxc_resolver = { version = "1.11.0", features = ["package_json_raw_json_api", "pnp", "yarn_pnp"] }
pico-args = "0.5.0"
walkdir = "2.5.0"
normalize-path = "0.2.1"
insta = { version = "1.40.0", features = ["filters"] }
itertools = "0.13.0"
indoc = "2.0.5"
regex = "1.11.0"

[dev-dependencies]
insta = { version = "1.40.0", features = ["yaml"] }
swc_ecma_parser = { version = "0.143.5" }
swc_ecma_transforms_testing = { version = "0.140.10" }
testing = { version = "0.35.19" }

# .cargo/config defines few alias to build plugin.
# cargo build-wasi generates wasm-wasi32 binary
# cargo build-wasm32 generates wasm32-unknown-unknown binary.
