name: Rust CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: cargo build --all-features
      - name: Tests
        run: cargo test
